package com.babichev.oleg.bioinformatic.problems;

import com.babichev.oleg.bioinformatic.core.DNA;

import java.util.List;

/**
 * Created by olegchuikin on 14/02/16.
 */
public class FindtheMostFrequentWordsinaString {

    public static void main(String[] args) {
        DNA dna = new DNA("GCAACATCCTCGGGTCCGTCTCGTTTTAGAGGGTCTCGTTTCGGGTCCGCAACATCCGTCTCGTTGTCTCGTTTCGGGTCCTTAGAGGTCGGGTCCTCGGGTCCCGGATCCTCGGATCCTTTAGAGGTTAGAGGGCAACATCCTTAGAGGGTCTCGTTTTAGAGGCGGATCCTTCGGGTCCGTCTCGTTTTAGAGGGTCTCGTTCGGATCCTTTAGAGGCGGATCCTTTAGAGGGTCTCGTTCGGATCCTTTAGAGGCGGATCCTGCAACATCCTCGGGTCCCGGATCCTTCGGGTCCGCAACATCCTTAGAGGTCGGGTCCCGGATCCTCGGATCCTGTCTCGTTGTCTCGTTGCAACATCCGCAACATCCCGGATCCTGTCTCGTTGCAACATCCGCAACATCCTCGGGTCCGTCTCGTTGCAACATCCTCGGGTCCTTAGAGGTTAGAGGGTCTCGTTTTAGAGGGTCTCGTTGCAACATCCTCGGGTCCTTAGAGGGCAACATCCGTCTCGTTGTCTCGTTTTAGAGGTCGGGTCCTTAGAGGTTAGAGGTCGGGTCCTCGGGTCCGTCTCGTTCGGATCCTGCAACATCCGTCTCGTTGTCTCGTTTTAGAGGCGGATCCTTCGGGTCCGTCTCGTTGCAACATCCTCGGGTCCGCAACATCCGCAACATCCCGGATCCTTTAGAGGTCGGGTCCTTAGAGGTTAGAGGTCGGGTCCTCGGGTCCTCGGGTCCGTCTCGTTGTCTCGTTGTCTCGTTGCAACATCCTCGGGTCCTCGGGTCCGCAACATCCGCAACATCCTCGGGTCCGTCTCGTTGTCTCGTTCGGATCCTTCGGGTCCTCGGGTCCGCAACATCCTCGGGTCCGCAACATCC");
        List<String> result = dna.getTheMostFrequentWordsOfLenghtK(14);
        for (String s : result) {
            System.out.printf(s + " ");
        }
    }
}
