package com.babichev.oleg.bioinformatic.problems;

import com.babichev.oleg.bioinformatic.core.DNA;
import com.babichev.oleg.bioinformatic.utils.GeneratorUtils;

/**
 * Created by olegchuikin on 18/02/16.
 */
public class Problem9 {

    public static void main(String[] args) {
        DNA dna = new DNA("TTATTTTGAATTCATTTATTTTGCCGTTTACGGAGGTTTATTTTCGACAGAACGACAGAAGAATTCATCGACAGAAGCCGTTTACGGAGGTGCCGTTTACGGAGGTGAATTCATGAATTCATGAATTCATCGGAGGTGCCGTTTAGCCGTTTATTATTTTCGGAGGTTTATTTTGAATTCATCGACAGAACGACAGAACGGAGGTTTATTTTCGGAGGTTTATTTTCGACAGAATTATTTTCGGAGGTGAATTCATCGACAGAACGACAGAATTATTTTGCCGTTTACGACAGAACGGAGGTCGACAGAACGGAGGTCGACAGAACGACAGAACGGAGGTGAATTCATGAATTCATGAATTCATGAATTCATTTATTTTGAATTCATCGGAGGTCGACAGAACGGAGGTGAATTCATGAATTCATCGACAGAACGACAGAAGCCGTTTAGCCGTTTAGAATTCATCGACAGAATTATTTTGAATTCATCGGAGGTCGACAGAATTATTTTCGGAGGTCGGAGGTTTATTTTTTATTTTCGACAGAAGCCGTTTACGGAGGTGAATTCATCGACAGAATTATTTTGAATTCATCGGAGGTCGGAGGTCGGAGGTCGACAGAACGGAGGTTTATTTTGAATTCATCGGAGGTCGGAGGTCGACAGAAGAATTCATGAATTCATTTATTTTCGACAGAAGCCGTTTACGACAGAAGAATTCATGAATTCATGCCGTTTACGGAGGTCGACAGAACGACAGAACGACAGAACGACAGAAGCCGTTTACGGAGGTGCCGTTTAGAATTCATGCCGTTTAGAATTCATCGACAGAACGGAGGTGAATTCATGCCGTTTATTATTTTTTATTTTCGGAGGT");

        for (String s : dna.getTheMostFrequentWordsOfLenghtK(6, 3)){
            System.out.printf(s + " ");
        }
    }

}
