package com.babichev.oleg.bioinformatic.problems;

import com.babichev.oleg.bioinformatic.core.DNA;
import com.babichev.oleg.bioinformatic.utils.GeneratorUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by olegchuikin on 18/02/16.
 */
public class Problem11 {
    public static void main(String[] args) {
        int k = 6;
        DNA dna = new DNA("GCCTGTAGAAAAGATATGATTTTTCGTCGATTTTCCTCCGCCGAGCAGAACATCATAAGGGGGCAATATTGCAAATTATGAAACGACCGATGTCGCTACGACACGCTACCACGGCAATGGTTGGTACCCTAGCTGTCCCTGGATAAGCCCTCTTAACACCTGGGCCCTTAACGTGGCTTTCGGTCGCTTGATTCGTCGCACGTGACGGAAGGACCCATCCACGGATGCACGACCCTAGGTATATGCAATTACCGATATGGAAGCACCGAGGACTCTCGGGCGATTCCGATATGACAGGGTGTCCATATCATAATCCTACGTCGGGAACTTTGCATGGGCCGGTCGACGACTCAGGCATGTAAGCCTTGCATGGTCATAGAATGTGGGCTCGCTGTCCAACTCATGTGGGCTGAGCGATATATGTTGCCCCAGCTTTATCGAGCCGGGCCTGGACGGGCTAGCGGGTTGCTGTGGTCTGCGACCTGTTGTGCCGCCACGTGCGAATGATTAAAATAATGCCACACATTGAGTCTTGTGCCGACAGGTTTTCATATGGAAATTTCTGTACTCCTACCGGTTCTTAGATCCAGGTCTAGTGAGGCACCGTGTGCGTTTCTTGCTTGCCTGAAGAAGTTTTCGTGCATCGGTAAGGCTATGAACCTTTAGAAGACGACAAGTATCAGTCAGTCTGCCAGTAGTAGATGCACGGCAGGATTTAAAGTTTCGGGTAAGCGAGAAAGGCCTGCAGAAGGATCACATTTGGTGGCCGCACGCAAGGCTAAGGCGTCCTTTCTAG");
        List<String> allSubs = GeneratorUtils.generateDNAStrings(k);

        for (String s : allSubs){
            System.out.printf(dna.numberOfSubstringAppearsInText(s) + " ");
        }

        for (int i = 0; i < allSubs.size(); i++){
            if (dna.numberOfSubstringAppearsInText(allSubs.get(i)) > 0 ){
//                System.out.println(i + ": " + dna.numberOfSubstringAppearsInText(allSubs.get(i)) );
            }
        }

    }
}
