package com.babichev.oleg.bioinformatic.problems;

import com.babichev.oleg.bioinformatic.core.DNA;

/**
 * Created by olegchuikin on 18/02/16.
 */
public class Problem10 {
    public static void main(String[] args) {
        DNA dna = new DNA("TAGCTAAGATAGCTAAGATGTTGTCTTAGCTAAGATAGCTAAGATGTTGTCTATGAATATAGCCCGGAAGCCCGGAAGCCCGGAATGAATATAGCCCGGAAGCCCGGATAGCTAAGAGATGTGATTAGCTAAGATAGCTAAGATGTTGTCTTGTTGTCTAGCCCGGAGATGTGATAGCCCGGAGATGTGATTGTTGTCTGATGTGATATGAATATATGAATATGATGTGATATGAATATATGAATATATGAATATAGCCCGGAAGCCCGGAAGCCCGGATGTTGTCTGATGTGATAGCCCGGAATGAATATTAGCTAAGAGATGTGATTAGCTAAGAGATGTGATGATGTGATGATGTGATTAGCTAAGAGATGTGATTGTTGTCTGATGTGATGATGTGATATGAATATGATGTGATTGTTGTCTAGCCCGGAAGCCCGGAAGCCCGGAGATGTGATAGCCCGGAAGCCCGGAATGAATATTGTTGTCTAGCCCGGATGTTGTCTTGTTGTCTTGTTGTCTTGTTGTCTTAGCTAAGAATGAATATAGCCCGGATGTTGTCTTGTTGTCTGATGTGATTGTTGTCTTAGCTAAGAAGCCCGGAAGCCCGGATGTTGTCTTGTTGTCTAGCCCGGATAGCTAAGAAGCCCGGATGTTGTCTTAGCTAAGATGTTGTCTGATGTGATGATGTGATTAGCTAAGAGATGTGATGATGTGATGATGTGATAGCCCGGAAGCCCGGAGATGTGATGATGTGATAGCCCGGATAGCTAAGAATGAATATGATGTGATTAGCTAAGATGTTGTCTAGCCCGGATAGCTAAGAAGCCCGGAGATGTGATTGTTGTCTTAGCTAAGAATGAATATTGTTGTCTTAGCTAAGAAGCCCGGAATGAATATATGAATATGATGTGATAGCCCGGATGTTGTCTATGAATATTGTTGTCT");

        for (String s : dna.getTheMostFrequentWordsOfLenghtK(7, 2, true)){
            System.out.print(s + " ");
        }
    }
}
